### ISSUE TITLE
support roxive theme

### ISSUE THREAD

**Issue by tabsl** [FlorianPalme/OXID-DebugBar#11]
support for roxive theme would be great ;-)

![ea46d4affcc54db52c25371af807e7](https://user-images.githubusercontent.com/1520658/48639366-a9be6a80-e9d3-11e8-865f-b5b07298367b.png)

**Comment by FlorianPalme** [comment]
Unterstützung ist nun integriert #12 und im 1.4.1-Release veröffentlicht.
