### ISSUE TITLE
Fehlende Übersetzungen auflisten

### ISSUE THREAD

**Issue by FlorianPalme** [FlorianPalme/OXID-DebugBar#4]
Es ist unter umständen ganz schick, in einem Tab die fehlenden Übersetzungen der aktuellen Seite anzeigt. 
Das ist in der Regel zwar ersichtlich, jedoch gibt es auch versteckte Elemente (z.B. Modal-Fenster o.ä.), bei welchen man fehlende Übersetzungen nicht auf den ersten Blick sieht.

**Comment by alfredbez** [comment]
Moin, vorweg: cooles Projekt, hatte ich auch mal vor zu bauen :wink: 

Um diese Funktion zu bauen, könnte man das Smarty-Plugin [`oxmultilang`](https://github.com/OXID-eSales/oxideshop_ce/blob/d14df91fd0b2c825c0ea8d95a2074600d82a9a4c/source/Core/Smarty/Plugin/function.oxmultilang.php) überschreiben und den entsprechenden Code ergänzen. Vielleicht ist dieser Pull Request hilfreich: https://github.com/OXID-eSales/oxideshop_ce/pull/520

**Comment by FlorianPalme** [comment]
Servus @alfredbez,

danke für deinen Input.

Beim Smarty-Plugin sehe ich 2 Probleme:
1. Es müsste die ganze Funktion ersetzt werden. Wenn möglich, versuche ich das immer zu vermeiden.
2. Es werden keine fehlenden Übersetzungen abgefangenen die direkt in PHP getätigt werden (`Language::translateString()`).

Daher werde ich eher in die [`translateString`](https://github.com/OXID-eSales/oxideshop_ce/blob/master/source/Core/Language.php#L418)-Methode reinspringen. Dann ist alles abgefangen und es wird keine Funktion ersetzt. :)

**Comment by FlorianPalme** [comment]
Im 1.4.0er Release integriert https://github.com/FlorianPalme/OXID-DebugBar/releases/tag/1.4.0
